name: 'venv setup'
description: 'configures venv, python and caches'

inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. If not set, the version in .python-version file will be used."
    default: ''
  cache-dependency-path:
    description: "Requirement files to install. Can be a glob pattern."
    default: '**/requirements*.txt'
  venv-dir:
    default: '.venv'
  install-cmd:
    description: 'Command to install python dependencies.'
  working-directory:
    description: 'The working directory to run the action in.'
    default: ${{ github.workspace }}
outputs:
  cache-hit:
    description: "A boolean value to indicate if a cache was restored"
    value: ${{ steps.cache-venv.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
        python-version-file: ${{ hashFiles(format('{0}/.python-version', inputs.working-directory)) == '' && '' || format('{0}/.python-version', inputs.working-directory) }}

    - run: echo '::remove-matcher owner=python::'
      shell: bash

    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57  # v4.2.0
      id: cache-venv
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.venv-dir }}
        key: setup-venv-${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-${{ steps.setup-python.outputs.python-path }}-${{ hashFiles(inputs.cache-dependency-path) }}-${{ inputs.install-cmd }}

    - run: python -m venv ${{ inputs.venv-dir }}
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: |
        SCRIPT_DIR="${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}"
        source ${{ inputs.venv-dir }}/${SCRIPT_DIR}/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
        echo "${VIRTUAL_ENV}/${SCRIPT_DIR}" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: ${{ inputs.install-cmd }}
      if: inputs.install-cmd != '' && steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
